### ISSUE TITLE
FFUpdater has crashed

### ISSUE THREAD

**Issue by codingepaduli** [Tobi823/ffupdater#18]
Hi,

in these days, my smartphone was without connection. I had the wire signal, but I was not able to navigate, so I experienced the following crash multiple times:

`
de.marmaro.krt.ffupdater.utils.ParamRuntimeException at BackgroundUpdateChecker.java:84 de.marmaro.krt.ffupdater.utils.ParamRuntimeException de.marmaro.krt.ffupdater.utils.ParamRuntimeException: background update check failed for FIREFOX_RELEASE at de.marmaro.krt.ffupdater.notification.BackgroundUpdateChecker.lambda$findAppsWithAvailableUpdates$1(BackgroundUpdateChecker.java:84) at de.marmaro.krt.ffupdater.notification.-$$Lambda$BackgroundUpdateChecker$35ZiPKEdROusULgHJI2328BkhpY.accept(Unknown Source:10) at j$.util.Map$-CC.$default$forEach(Map.java:5) at j$.util.Map$-EL.forEach(Map.java:6) at de.marmaro.krt.ffupdater.notification.BackgroundUpdateChecker.findAppsWithAvailableUpdates(BackgroundUpdateChecker.java:75) at de.marmaro.krt.ffupdater.notification.BackgroundUpdateChecker.doBackgroundCheck(BackgroundUpdateChecker.java:62) at de.marmaro.krt.ffupdater.notification.BackgroundUpdateChecker.doWork(BackgroundUpdateChecker.java:47) at androidx.work.Worker$1.run(Worker.java:85) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) Caused by: java.util.concurrent.ExecutionException: de.marmaro.krt.ffupdater.utils.ParamRuntimeException: can't consume API interface https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.arm64-v8a/artifacts/public/chain-of-trust.json at java.util.concurrent.FutureTask.report(FutureTask.java:123) at java.util.concurrent.FutureTask.get(FutureTask.java:207) at de.marmaro.krt.ffupdater.notification.BackgroundUpdateChecker.lambda$findAppsWithAvailableUpdates$1(BackgroundUpdateChecker.java:77) ... 10 more Caused by: de.marmaro.krt.ffupdater.utils.ParamRuntimeException: can't consume API interface https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.release.latest.arm64-v8a/artifacts/public/chain-of-trust.json at de.marmaro.krt.ffupdater.metadata.fetcher.ApiConsumer.consume(ApiConsumer.java:43) at de.marmaro.krt.ffupdater.metadata.fetcher.MozillaCiConsumer.consume(MozillaCiConsumer.java:22) at de.marmaro.krt.ffupdater.metadata.fetcher.Firefox.call(Firefox.java:47) at de.marmaro.krt.ffupdater.metadata.fetcher.Fetcher.fetchAvailableMetadata(Fetcher.java:74) at de.marmaro.krt.ffupdater.metadata.fetcher.Fetcher.call(Fetcher.java:56) at de.marmaro.krt.ffupdater.metadata.fetcher.Fetcher.call(Fetcher.java:15) at java.util.concurrent.FutureTask.run(FutureTask.java:266) ... 3 more Caused by: java.net.ConnectException: Failed to connect to firefox-ci-tc.services.mozilla.com/35.190.5.182:443 at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143) at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:207) at java.net.URLConnection.getContentEncoding(URLConnection.java:529) at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:142) at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:26) at de.marmaro.krt.ffupdater.metadata.fetcher.ApiConsumer.consume(ApiConsumer.java:33) ... 9 more Android Version: 28 Device Manufacturer: asus Device Model: ASUS_X01BDA 
`

Thank you for your work.

**Comment by Tobi823** [comment]
The original error is: 
        Caused by: java.net.ConnectException: Failed to connect to firefox-ci-tc.services.mozilla.com/35.190.5.182:443

Does this error occur regularly? (I think that you misconfigured your smartphone - maybe your selected DNS-Server is unreliable, your mobile data config is strange etc.)

The background update checker should only run if your smartphone is connected to the internet.
But obviously, the update checker runs even if the internet is not available.

I'm afraid that I can't fix this bug.

But I can add an option, after how many successive errors the error notification should be displayed.
What do you think?

**Comment by Tobi823** [comment]
BTW similar bug https://gitlab.com/Tobiwan/ffupdater/-/issues/1

**Comment by codingepaduli** [comment]
No,

I did NOT misconfigured anything, I did NOT changed my DNS-Server. It was only a temporary issue caused by the mobile phone carrier; After few days, FFUpdater worked greatly again. 

I don't ask to set an option to count how many successive errors happens before display the notification.

I just think that only developers are able to understand the stacktrace shown, so I think the stracktrace should be available, but common user should see an understandable error message.

 Like  Marc Dequènes (Duck) @duck-rh  say in the bug https://gitlab.com/Tobiwan/ffupdater/-/issues/1  , a simple notification saying "Due to network connectivity problem the background check failed" would be more useful. And a button to click in order to see the stacktrace and send the bug.

Thanks.

**Comment by borisovg** [comment]
I started having the same issue several weeks ago. It is annoying having to dismiss this useless message every time from my notifications.

**Comment by Tobi823** [comment]
The issue should now be fixed (in version 71.0.0).

FFUpdater retries up to two times before crashing (when contacting the server for available versions)

**Comment by duck-rh** [comment]
@Tobi823 it's nice but that does not solve the problem of the error message. Not anyone is able to make sense of traces.

**Comment by Tobi823** [comment]
@duck-rh What do you think about this?

![image](https://user-images.githubusercontent.com/10066140/108133316-a8011700-70b4-11eb-8894-af23070c3243.png)
> "FFUpdater hasn't been able to check for updates in the background. Maybe this has been caused by a network connectivity issue or an unknown bug. If this error occurs regularly, please report it. Click to view the technical error message."

The "background update check failed" can be triggered by a network connectivity issue or an unknown app. Displaying "Due to network connectivity problem ..." would be misleading.

**Comment by duck-rh** [comment]
@Tobi823 that's better. Is there no way to separate network issues and bugs, like filtering the exception? I mean you probably do not want people to bother you with tickets each time they have a bad connection. So if you could check the exception raised in order to clearly distinguish connectivity issues then you could have two messages, one to tell the person to check their connection and the other to report a bug, But that's just a suggestion.

**Comment by Tobi823** [comment]
> Is there no way to separate network issues and bugs, like filtering the exception?

Not with absolute certainty. But I can make a good guess.

> then you could have two messages

Good idea. Why didn't I come up with this myself? :smile: 

What do you think about these messages?

If it's likely a temporary connectivity issue => 
_It's likely that the background check failed due to a temporary network connectivity issue. But if this error occurs more than once a week, please report it. Click to view the error log._

If it's certain a real bug =>
_Due to an unknown bug the background check failed. Please report this error. Click to view the error log._

**Comment by duck-rh** [comment]
looks fine, thanks
