### ISSUE TITLE
Crash while installing firefox nightly from ffupdater

### ISSUE THREAD

**Issue by PsykoRider** [Tobi823/ffupdater#327]
Stacktrace:
```
java.lang.IllegalStateException: LifecycleOwner de.marmaro.krt.ffupdater.DownloadActivity@43d8035 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
	at androidx.activity.result.f.c(SourceFile:92)
	at de.marmaro.krt.ffupdater.installer.impl.IntentInstaller.onCreate(Unknown Source:21)
	at androidx.lifecycle.FullLifecycleObserverAdapter.a(Unknown Source:42)
	at androidx.lifecycle.p$a.a(SourceFile:18)
	at androidx.lifecycle.p.a(SourceFile:115)
	at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:104)
	at de.marmaro.krt.ffupdater.DownloadActivity.fetchDownloadInformationOrUseCache(Unknown Source:276)
	at de.marmaro.krt.ffupdater.DownloadActivity.checkIfEnoughStorageAvailable(SourceFile:13)
	at de.marmaro.krt.ffupdater.DownloadActivity.checkIfStorageIsMounted(Unknown Source:14)
	at de.marmaro.krt.ffupdater.DownloadActivity.startInstallationProcess(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startInstallationProcess(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$onCreate$3.invokeSuspend(Unknown Source:28)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: i4.j0: [p1{Cancelling}@ea8dbab, Dispatchers.Main]
Timestamp: 2023-01-30T11:34:47.821

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.0 (126) release |
| Device | POCO F2 Pro (lmi_eea, lmi, lmi) |
| Manufacturer | POCO (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-xztq7, builder, release-keys, 1672051495000 |

**Comment by Tobi823** [comment]
@PsykoRider @toxcien I can't reproduce this bug but I think that I fixed the bug. Can you try this version? 
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/10551415/ffupdater-release.zip)

**Comment by PsykoRider** [comment]
Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_NIGHTLY in the foreground.
      at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:171)
      at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
      at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
      at w3.a.resumeWith(Unknown Source:8)
      at i4.l0.run(Unknown Source:102)
      at android.os.Handler.handleCallback(Handler.java:938)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loopOnce(Looper.java:210)
      at android.os.Looper.loop(Looper.java:299)
      at android.app.ActivityThread.main(ActivityThread.java:8293)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: INSTALL_FAILED_ABORTED: Permission denied. The installation failed because it was actively aborted.
      at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.fail(Unknown Source:4)
      at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.handleAppInstallationResult(Unknown Source:31)
      at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$handleAppInstallationResult(Unknown Source:0)
      at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$registerIntentReceiver$1.onReceive(Unknown Source:2)
      at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
      at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
      ... 8 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.1 (127) release |
| Device | POCO F2 Pro (lmi_eea, lmi, lmi) |
| Manufacturer | POCO (Xiaomi) |
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-xztq7, builder, release-keys, 1672051495000 |

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by toxcien** [comment]
> @PsykoRider @toxcien I can't reproduce this bug but I think that I fixed it. Can you try this version? [ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/10551415/ffupdater-release.zip) 

I was trying to update Mull to 109.2 when that crash happened but I fixed it with clearing cache and clearing data on settings, so that isn't problem for me anymore. But I don't know if my crash report is related to installing Firefox Nightly.

**Comment by PsykoRider** [comment]
It's not the first time I try clearing the cache, even reinstalling the application and still the problem persists, either at the same time or later. Anyway, thanks for your great effort.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PsykoRider** [comment]
Right

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mehtashrey** [comment]
I had a similar bug while installing Firefox beta. 

Stacktrace:
```
java.lang.IllegalArgumentException: Unrecognized stream
	at android.content.pm.PackageInstaller$Session.fsync(PackageInstaller.java:1180)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.copyApkToSession(Unknown Source:91)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.install(Unknown Source:31)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller.access$install(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.impl.SessionInstaller$executeInstallerSpecificLogic$3.invokeSuspend(Unknown Source:39)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: i4.j0: [p1{Cancelling}@c9164e4, Dispatchers.Main]
Timestamp: 2023-02-02T18:27:31.067

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.1 (127) release |
| Device | SM-M536B (m53xnnxx, m53x, m53x) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6923, dpi, release-keys, 1673856816000 |

**Comment by PsykoRider** [comment]
More crash.

Stacktrace:
```
java.lang.RuntimeException: Failed to install FIREFOX_NIGHTLY in the foreground.
      at de.marmaro.krt.ffupdater.DownloadActivity.installApp(Unknown Source:171)
      at de.marmaro.krt.ffupdater.DownloadActivity.access$installApp(Unknown Source:0)
      at de.marmaro.krt.ffupdater.DownloadActivity$installApp$1.invokeSuspend(Unknown Source:11)
      at w3.a.resumeWith(Unknown Source:8)
      at i4.l0.run(Unknown Source:102)
      at android.os.Handler.handleCallback(Handler.java:938)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loopOnce(Looper.java:210)
      at android.os.Looper.loop(Looper.java:299)
      at android.app.ActivityThread.main(ActivityThread.java:8293)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: de.marmaro.krt.ffupdater.installer.exception.InstallationFailedException: Can't validate the signature of the APK file.
      at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(Unknown Source:330)
      at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.access$install2Internal(Unknown Source:0)
      at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller$startInstallation$2.invokeSuspend(Unknown Source:32)
      at w3.a.resumeWith(Unknown Source:8)
      at i4.l0.run(Unknown Source:102)
      at kotlinx.coroutines.internal.e.run(Unknown Source:11)
      at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
      at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
Caused by: java.lang.IllegalArgumentException: Can't extract the signature from APK file '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fenix_2023-02-03 17:06.apk', length: 27975860, absolutePath: /storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org_mozilla_fenix_2023-02-03 17:06.apk, isFile: true, execute: false, read: true, write: false
      at de.marmaro.krt.ffupdater.security.PackageManagerUtil.getPackageArchiveInfo(SourceFile:153)
      at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invokeSuspend(Unknown Source:48)
      at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(Unknown Source:8)
      at de.marmaro.krt.ffupdater.security.FingerprintValidator$checkApkFile$2.invoke(Unknown Source:4)
      at i4.d0.y(SourceFile:5)
      at a2.i.k0(SourceFile:86)
      at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(SourceFile:9)
      at de.marmaro.krt.ffupdater.installer.impl.AbstractAppInstaller.install2Internal(Unknown Source:142)
      ... 7 more
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.2 (128) release |
| Device | POCO F2 Pro (lmi_eea, lmi, lmi) |
| Manufacturer | POCO (Xiaomi) |
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | non-pangu-pod-xztq7, builder, release-keys, 1672051495000 |

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tobi823** [comment]
@PsykoRider This is a different bug - I will move it to a new ticket
