### ISSUE TITLE
Crash whilst downloading Chromium

### ISSUE THREAD

**Issue by runninghamster0** [Tobi823/ffupdater#340]
Hi,

Upon trying to install Chromium, the app crashes. It reaches 100% in the download progress bar and crashes immediately afterwards.

Thank you

Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(SourceFile:121)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(SourceFile:546)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: i4.j0: [p1{Cancelling}@1ecd8c4, Dispatchers.Main]
Timestamp: 2023-02-13T17:02:48.106

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.5 (131) release |
| Device | Pixel 7 (panther, panther, panther) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a |
| Android version | 13 (SDK: 33) |
| OS | abfarm-release-2004-0153, android-build, release-keys, 1673310668000 |

**Comment by Sprungles** [comment]
I received a report with the following:

Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(SourceFile:121)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(SourceFile:546)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: i4.j0: [p1{Cancelling}@6875a88, Dispatchers.Main]
Timestamp: 2023-02-13T10:56:11.440

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.5 (131) release |
| Device | PH-1 (lineage_mata, mata, Mata) |
| Manufacturer | essential (Essential Products) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | ODS-PROD, nolenjohnson, release-keys, 1675913280000 |

**Comment by Wojtaz0w** [comment]
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(SourceFile:121)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(SourceFile:546)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(Unknown Source:0)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(Unknown Source:11)
	at w3.a.resumeWith(Unknown Source:8)
	at i4.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
	Suppressed: i4.j0: [p1{Cancelling}@519b12e, Dispatchers.Main]
Timestamp: 2023-02-21T22:27:41.631

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.5 (131) release |
| Device | Redmi 9 (lineage_lancelot, lancelot, mt6768) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | android-build, nobody, release-keys, 1671362473000 |         
Can confirm.

**Comment by APPLESOFT98** [comment]
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:17)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:330)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9cb0ac3, Dispatchers.Main]
Timestamp: 2023-02-22T19:24:24.721
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.6 (132) release |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1675073918000 |

**Comment by APPLESOFT98** [comment]
Just updated now and the issue is not only while downloading Chromium on Android/AOSP 13, but on Firefox Beta and Nightly from Firefox's repository as well. Tried on different devices but seems like a problem with Android 13 (except Firefox Beta and Nightly, I have that on every devices now).

Chromium's stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:17)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:330)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1d8d935, Dispatchers.Main]
Timestamp: 2023-02-27T19:26:31.161
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.7 (133) release |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1675073918000 |

**Comment by Tobi823** [comment]
Should be fixed in 77.7.8

**Comment by APPLESOFT98** [comment]
> Should be fixed in 77.7.8
Firefox Nightly's download seems working now, Chromium still doesn't.

Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:17)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:330)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@564a4d1, Dispatchers.Main]
Timestamp: 2023-02-28T20:31:39.477

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.8 (134) release |
| Device | SM-G991B (o1sxeea, o1s, exynos2100) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | SWDK6118, dpi, release-keys, 1675073918000 |
