### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by fusionneur** [Tobi823/ffupdater#485]
Error seems to be related to tor browser alpha

Stacktrace:
```
java.lang.IllegalStateException: Can't find download url with regex pattern: \Qhttps://dist.torproject.org/torbrowser/\E([0-9a-z.]{4,})\Q/tor-browser-\E[0-9a-z.]{4,}+\Q-android-aarch64-multi.apk\E.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha.findVersionAndDownloadUrl(TorBrowserAlpha.kt:68)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha.access$findVersionAndDownloadUrl(TorBrowserAlpha.kt:23)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowserAlpha.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f70c25d, Dispatchers.Main]

```
Logs:
```
java.lang.IllegalStateException: Can't find download url with regex pattern: \Qhttps://dist.torproject.org/torbrowser/\E([0-9a-z.]{4,})\Q/tor-browser-\E[0-9a-z.]{4,}+\Q-android-aarch64-multi.apk\E.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha.findVersionAndDownloadUrl(TorBrowserAlpha.kt:68)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha.access$findVersionAndDownloadUrl(TorBrowserAlpha.kt:23)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowserAlpha$findVersionAndDownloadUrl$1.invokeSuspend(TorBrowserAlpha.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f70c25d, Dispatchers.Main]

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 78.1.2 (151) release F-Droid/other |
| Device | unknown (unknown, unknown, unknown) |
| Manufacturer | unknown (unknown) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 12 (SDK: 31) |
| OS | unknown, unknown, unknown, 0 |

**Comment by Tobi823** [comment]
Thans for the info. The problem is now fixed in 78.1.4

**Comment by ghdotc** [comment]
Still crashes for me on f-droid 78.1.5


123456789101112131415161718
time: 1694170159770
msg: java.lang.IllegalStateException: Check failed.
stacktrace: java.lang.IllegalStateException: Check failed.
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24)
	at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66ac486, Dispatchers.Main]
GitHub

**Comment by ghdotc** [comment]
> Still crashes for me on f-droid 78.1.5
> 
> 123456789101112131415161718 time: 1694170159770 msg: java.lang.IllegalStateException: Check failed. stacktrace: java.lang.IllegalStateException: Check failed. at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:82) at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer.getLatestUpdate(FdroidConsumer.kt:24) at de.marmaro.krt.ffupdater.network.fdroid.FdroidConsumer$getLatestUpdate$1.invokeSuspend(FdroidConsumer.kt:0) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7936) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854) Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66ac486, Dispatchers.Main] GitHub

If I use installer from io.github.muntashirakon.AppManager, then it'll show me this error
![1000004813](https://github.com/Tobi823/ffupdater/assets/142530731/478577a7-279a-4fa4-a734-ade576289410)

**Comment by MichaelPerron** [comment]
With me everything works:
Brave
Chromium
Firefox Nightly
Tor Browser Alpha

**Comment by ghdotc** [comment]
> With me everything works: Brave Chromium Firefox Nightly Tor Browser Alpha

I can't eve open this thing, cuz it crashes when I try to do it.

**Comment by ghdotc** [comment]
> > With me everything works: Brave Chromium Firefox Nightly Tor Browser Alpha
> 
> I can't even open this thing, cuz it crashes when I try to do that.

Latest ver that dosen't crash for me is 77.7.13. Every ver after that is crashing.
