### ISSUE TITLE
background check failed

### ISSUE THREAD

**Issue by TonyApuzzo** [Tobi823/ffupdater#689]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ...
2. ...
3. ...

**Expected behavior**
Please give a clear and concise description of what you expected to happen.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.3.1 (177) release Github |
| Device | Pixel 9 Pro (caiman, caiman, caiman) |
| Manufacturer | google (Google) | 
| Supported ABIs | arm64-v8a |
| Android version | 15 (SDK: 35) |
| OS | r-eaf9838018e7e7ac-sl1b, android-build, release-keys, 1734554758000 |

**Comment by pherpatdev2** [comment]
Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:142)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:49)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 79.3.1 (177) release Github |
| Device | SM-N960F (crownltexx, crownlte, exynos9810) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 10 (SDK: 29) |
| OS | SWDH4609, dpi, release-keys, 1658369212000 |

**Comment by Tobi823** [comment]
The bug should be fixed in 80.0.0

**Comment by groszdaniel** [comment]
This still happens time to time on 80.0.0. I turn off WiFi and mobile data when I don't use the internet, and I sometimes don't use this device for days.

Stacktrace:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Logs:
```
de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 80.0.0 (178) release Github |
| Device | M2006C3MNG (angelican_eea, angelican, angelican) |
| Manufacturer | Redmi (Xiaomi) | 
| Supported ABIs | armeabi-v7a, armeabi |
| Android version | 14 (SDK: 34) |
| OS | android-build, nobody, release-keys, 1741348911000 |         

Some more logs in the crash info that the "Copy crash report" button doesn't copy for some reason:

```
--------- beginning of main
04-15 03:03:17.933 I/FFUpdater(14309): InstalledAppsCache: Update cache of installed apps.
04-15 03:03:17.991 I/FFUpdater(14309): BackgroundJob:: Execute background job.
04-15 03:03:18.091 I/FFUpdater(14309): InstalledAppsCache: Cache was updated.
04-15 03:03:18.097 I/FFUpdater(14309): BackgroundJob:: Start BackgroundWork
04-15 03:03:18.097 I/FFUpdater(14309): StorageCleaner: Delete possible cached files of BRAVE, BRAVE_BETA, BRAVE_NIGHTLY, CHROMIUM, CROMITE, DUCKDUCKGO_ANDROID, FAIREMAIL, FENNEC_FDROID, FIREFOX_BETA, FIREFOX_FOCUS, FIREFOX_FOCUS_BETA, FIREFOX_KLAR, FIREFOX_NIGHTLY, FIREFOX_RELEASE, K9MAIL, ORBOT, PRIVACY_BROWSER, THORIUM, THUNDERBIRD_BETA, TOR_BROWSER, TOR_BROWSER_ALPHA, VIVALDI
04-15 03:03:18.107 I/FFUpdater(14309): BackgroundJob:: Enqueuing work requests for: {[ICERAVEN]}
04-15 03:03:18.120 I/FFUpdater(14309): BackgroundJob:: Done enqueuing work requests.
04-15 03:03:18.278 I/FFUpdater(14309): AppUpdater:: Start doWork for ICERAVEN
04-15 03:03:18.278 I/FFUpdater(14309): AppUpdater:: Start for ICERAVEN.
04-15 03:03:18.318 E/FFUpdater(14309): AppUpdater:: Failed to update app
04-15 03:03:18.318 E/FFUpdater(14309): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 03:03:18.318 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 03:03:18.318 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 03:03:18.318 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 03:03:18.318 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
04-15 03:08:14.929 I/FFUpdater(14309): AppUpdater:: Start doWork for ICERAVEN
04-15 03:08:14.929 I/FFUpdater(14309): AppUpdater:: Start for ICERAVEN.
04-15 03:08:14.983 E/FFUpdater(14309): AppUpdater:: Failed to update app
04-15 03:08:14.983 E/FFUpdater(14309): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 03:08:14.983 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 03:08:14.983 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 03:08:14.983 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 03:08:14.983 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
04-15 03:29:11.949 I/FFUpdater(14309): AppUpdater:: Start doWork for ICERAVEN
04-15 03:29:11.949 I/FFUpdater(14309): AppUpdater:: Start for ICERAVEN.
04-15 03:29:11.975 E/FFUpdater(14309): AppUpdater:: Failed to update app
04-15 03:29:11.975 E/FFUpdater(14309): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 03:29:11.975 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 03:29:11.975 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 03:29:11.975 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 03:29:11.975 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
04-15 05:49:02.683 I/FFUpdater(14309): AppUpdater:: Start doWork for ICERAVEN
04-15 05:49:02.683 I/FFUpdater(14309): AppUpdater:: Start for ICERAVEN.
04-15 05:49:02.786 E/FFUpdater(14309): AppUpdater:: Failed to update app
04-15 05:49:02.786 E/FFUpdater(14309): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 05:49:02.786 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 05:49:02.786 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 05:49:02.786 E/FFUpdater(14309): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 05:49:02.786 E/FFUpdater(14309): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
04-15 05:53:37.995 I/FFUpdater(14856): InstalledAppsCache: Update cache of installed apps.
04-15 05:53:38.043 I/FFUpdater(14856): AppUpdater:: Start doWork for ICERAVEN
04-15 05:53:38.043 I/FFUpdater(14856): AppUpdater:: Start for ICERAVEN.
04-15 05:53:38.071 E/FFUpdater(14856): AppUpdater:: Failed to update app
04-15 05:53:38.071 E/FFUpdater(14856): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 05:53:38.071 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 05:53:38.071 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 05:53:38.071 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 05:53:38.071 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
04-15 05:53:38.103 I/FFUpdater(14856): InstalledAppsCache: Cache was updated.
04-15 05:53:38.104 I/FFUpdater(14856): BackgroundJob:: Start BackgroundWork
04-15 05:53:38.107 I/FFUpdater(14856): StorageCleaner: Delete possible cached files of BRAVE, BRAVE_BETA, BRAVE_NIGHTLY, CHROMIUM, CROMITE, DUCKDUCKGO_ANDROID, FAIREMAIL, FENNEC_FDROID, FIREFOX_BETA, FIREFOX_FOCUS, FIREFOX_FOCUS_BETA, FIREFOX_KLAR, FIREFOX_NIGHTLY, FIREFOX_RELEASE, K9MAIL, ORBOT, PRIVACY_BROWSER, THORIUM, THUNDERBIRD_BETA, TOR_BROWSER, TOR_BROWSER_ALPHA, VIVALDI
04-15 06:09:01.921 I/FFUpdater(14856): AppUpdater:: Start doWork for ICERAVEN
04-15 06:09:01.921 I/FFUpdater(14856): AppUpdater:: Start for ICERAVEN.
04-15 06:09:01.950 E/FFUpdater(14856): AppUpdater:: Failed to update app
04-15 06:09:01.950 E/FFUpdater(14856): de.marmaro.krt.ffupdater.background.exception.AppUpdaterRetryableException: Simple network test was not successful. Retry later.
04-15 06:09:01.950 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater.isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:146)
04-15 06:09:01.950 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater.access$isUpdateCheckPossible-gIAlu-s(AppUpdater.kt:50)
04-15 06:09:01.950 E/FFUpdater(14856): 	at de.marmaro.krt.ffupdater.background.AppUpdater$isUpdateCheckPossible$1.invokeSuspend(AppUpdater.kt:0)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-15 06:09:01.950 E/FFUpdater(14856): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
